Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
 
    # Customize the amount of memory on the VM:
    vb.cpus = 2
    vb.memory = "8192"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

  # this is to ensure we get in trouble when the vagrant-vbguest plugin is not installed!
  config.vbguest.auto_update = false
end
