Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  # see https://github.com/dotless-de/vagrant-vbguest/issues/367#issuecomment-581360264
  config.vm.box_url = "http://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.1.1911-20200113.3.x86_64.vagrant-virtualbox.box"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
 
    # Customize the amount of memory on the VM:
    vb.cpus = 2
    vb.memory = "8192"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

  # this is to ensure we get in trouble when the vagrant-vbguest plugin is not installed!
  config.vbguest.auto_update = true
end
